[package]
name = "console"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parse_args = { path = "lib/arg_parser" }
rs_image = { version = "0.1.0", path = "../lib" }
colored = { version = "2.0.0" }
unicode-segmentation = { version = "1.10.1" }
termsize = { version = "0.1.6" }